name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: npm i -g --force corepack && corepack enable
      - name: Install dependencies
        run: pnpm i
      - run: npx nuxi@latest module add @nuxthub/core
      - name: add @nuxthub/core to .nuxtrc
        run : echo "modules[]= @nuxthub/core" >> .nuxtrc


      - name: Build application
        run: pnpm build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        id: deploy
        with:
          project-key: content-v3-depl-6e0f
